### ISSUE TITLE
856 - Federal Impact Assessment Challenge needs file upload

### ISSUE THREAD

**Issue by greensteph** [GSA/challenges-and-prizes#162]
_archived-challenges/856-federal-impact-assessment-challenge.md

needs a pdf file uploaded line 47:

FIA Challenge Instructions to help you craft your entry.

**Comment by twgsa16** [comment]
pull request #173 adds file, references file as site.base URL, and added target blanks and rel noopeners to FIA challenge

**Comment by greensteph** [comment]
closed by #173
