### ISSUE TITLE
www.challenge.gov/list

### ISSUE THREAD

**Issue by twgsa16** [GSA/challenges-and-prizes#172]
On any search results page, the Challenge.gov logo points to https://www.challenge.gov/list/. 

This page provides a Federalist 404 error. Can it be pointed back to the main Challenge.gov listing/home page?

**Comment by greensteph** [comment]
@twgsa16  I am not able to duplicate this issue. Let's discuss on today's call.

**Comment by twgsa16** [comment]
As discuss in our development call, this issue likely stems from a review of an older branch. It is not replicable on the site. Closing this out.
