### ISSUE TITLE
Tagline

### ISSUE THREAD

**Issue by twgsa16** [GSA/challenges-and-prizes#191]
Facebook pulls in "Challenges of Challenge" when the Challenge.gov URL is typed in for posting.

<img width="796" alt="Screen Shot 2019-06-19 at 9 07 32 PM" src="https://user-images.githubusercontent.com/16917415/59811308-3ec17300-92d7-11e9-93e1-626a789a37c6.png">
 
Not sure where the tagline is generated in the system, looks to be some form of metadata, but is it possible to update to the existing tagline "Government Challenges, Your Solutions"?

**Comment by greensteph** [comment]
The url you are using is pulling in the old metadata from IdeaScale. You need add the s in the https to pull in the new metadata. @twgsa16  

<img width="1012" alt="Screenshot 2019-06-20 06 16 13" src="https://user-images.githubusercontent.com/11343071/59848758-33943480-9323-11e9-9ed0-9421f6c391e1.png">

<img width="1096" alt="Screenshot 2019-06-20 06 15 44" src="https://user-images.githubusercontent.com/11343071/59848769-3a22ac00-9323-11e9-9ec8-9e1324c4b3b6.png">
