### ISSUE TITLE
Update Blog Content Settings

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/challenges-and-prizes#1944]
As a Challenge.Gov user, in order to trust challenge.gov content as authoritative source of information about federal challenges, I would like to navigate through blog posts without interruptions and without seeing "broken" pages.

Acceptance criteria:

- [x] Blog links on the site are updated to link to the latest blog post  (skipping blog landing page)
- [x] Blog post link limit on the side navigation is increased to show more than 3 latest posts

**Comment by r-bartlett-gsa** [comment]
@kkrug / @jdonis  This was merged to staging branch on challenges-and-prizes repo and since we have yet to establish our workflow process moving forward, I wanted to check-in with you on how to get this to production. For challenges-and-prizes is master or main a production branch? Some of the previous content changes were merged to master directly (https://github.com/GSA/challenges-and-prizes/pull/1941), so I assume master is production, and main is dev?

**Comment by kkrug** [comment]
@r-bartlett-gsa yes master is production and main is dev
