### ISSUE TITLE
Update Pages configuration to reflect new branch names

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/challenges-and-prizes#1949]
As a site engineer, in order to ensure the Pages site functions correctly, I would like to update branch names throughout site code and in Pages configuration.

Acceptance criteria:

- [x] Pages configuration is updated to reflect new branch names
- [x] Templates are updated to reflect new branch names

**Comment by jdonis** [comment]
@r-bartlett-gsa ready for QA
