### ISSUE TITLE
Manage Challenge & Prize Listserv

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1967]
- [x] Add new members 
- [x] Remove bounced email addresses
- [x] Review & approve listserv posts
- [x] Download and prepare listserv report
- [x] Add report to monthly data file

**Comment by cqslayton** [comment]
Update: Worked with a Listserv member to find and remove their email address. Approved 3 new members as they requested. Rejected 1 request with non-gov email address. Approved 2 posts. 726 subscribers.

Doc: [Sprint 97 Listserv](https://drive.google.com/file/d/1Fd73ieHuSdCezY9DRNi4i9WqSdKBYgf6/view?usp=drive_link)

**Comment by cqslayton** [comment]
Sprint 98: Added 1 user. Deleted 2 users. 4 users signed off. Approved 12 posts. 714 subscribers.

Doc: [Sprint 98 Listerv Activity report](https://drive.google.com/file/d/1PPl1egezurWWTA3GDTvAvEybK2iTH3Z4/view?usp=drive_link)
