### ISSUE TITLE
Customer Support for Challenge.gov Platform

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1968]
As a Challenge.gov customer, I want to have support using the Challenge.gov platform.

- [x] Monitor the team@challenge.gov inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update challenge tracker document

**Comment by cqslayton** [comment]
Sprint 97: 20 tickets. 5 public, 15 federal. 3 good with comment. 100% Satisfaction rating. Led a demo for Department of Ed Attendance Challenge manager and SBA Cyber Challenge team.

Comments:

- We have had an amazing experience with GSA TTS Solutions Support. Extremely helpful and very responsive. Thank you!
- Quinn and her colleagues are always very helpful.
- GSA's support via Challenge.gov has always been top notch. They are proactive and responsive and very accommodating. I would consider them best in class.

Doc: [Sprint 97 Zendesk tickets](https://docs.google.com/spreadsheets/d/1Sh-XmPtP3o3U4jIVkqRz-Dw0FmNdV-tk/edit?usp=drive_link&ouid=115868439013136820772&rtpof=true&sd=true)

**Comment by cqslayton** [comment]
Sprint 98: 31 tickets (+11). 3 public, 28 federal. 3 good ratings, 0 bad. 100% Satisfaction rating. Provided demo to the Navy team looking to switch to using Challenge.gov for the submission portal.
Doc: [Sprint 98 Zendesk tickets](https://docs.google.com/spreadsheets/d/1QsoKHLojibG9Hyrq5S2V7Honb6JnCa0V/edit?usp=drive_link&ouid=115868439013136820772&rtpof=true&sd=true)
