### ISSUE TITLE
Department of Energy Webinar | September 17

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1969]
As a Challenge.gov program team member, I want to promote Challenge.gov and build relationships with federal and public audiences by producing a webinar featuring the U.S. Department of Energy American Made program.

Event Planning
- [x] Confirm event date/time, agenda, title, and description
- [x] Captioner request
- [x] Webinar increase +100 request

Event Promotion
- [x] Create branding for social media
- [x] Develop communications plan
- [x] Build Zoom registration/event
- [x] Source tracking links created
- [x] Submit post-event survey for PRA approval
- [x] Open registration and promote event

Event Logistics
- [x] Content preparation (Finalize agenda, questions, and run-of-show)
- [x] Slides Accessibility Review
- [x] Technical rehearsal

Post Event
- [x] Send thank you and any follow up communications to speakers
- [x] Send thank you email with survey link to registration list
- [x] Capture, analyze, and report survey data
- [x] Close survey

Post Event Resources
- [x] Send event slides to Challenge  & Prize listserv
- [x] Edit event video for accessibility and 508 compliance
- [x] Post event video on Challenge.gov YouTube
- [x] Share video with listserv, registration list, social media (LinkedIn and Facebook), and include in PubNews
- [x] Share YouTube video link with DOE partners to cross-promote
- [x] Draft post event blog

**Comment by kgkempe** [comment]
Sent the [Event Brief](https://docs.google.com/document/d/1b7M2H335e4Seum1U9u8pi8bdfeq8D0ueDFOoMkKi-jY/edit?usp=sharing) to DOE contacts. Ask them to confirm title and event timing.

**Comment by L-Bar11** [comment]
Please add "Create social media content & publish" as a check box, thank you.

**Comment by L-Bar11** [comment]
Should we link to the event brief? If so, here is the link: https://docs.google.com/document/d/1b7M2H335e4Seum1U9u8pi8bdfeq8D0ueDFOoMkKi-jY/edit

**Comment by cqslayton** [comment]
Updated the tracking links doc: https://docs.google.com/spreadsheets/d/1jdF4W_DI0W2-GBkzqBsPdQzw9UfjQiBT-ADXhSOiOow/edit?gid=0#gid=0

**Comment by kgkempe** [comment]
Need to add "Update Events Page" as check box - both in the event preparation section and in the post event section.

**Comment by cqslayton** [comment]
Registrations as of 8/19: 103

**Comment by kgkempe** [comment]
Schedule technical rehearsal with DOE on September 16.

**Comment by fbaloca** [comment]
Post-event survey submitted for PRA approval today 8/21

**Comment by fbaloca** [comment]
Post-event survey PRA Fast Track 7 day wait notification 8/27

**Comment by fbaloca** [comment]
Completed run of show draft and sent to DOE partners along with bio/headshot and slides request. PRA approval received 9/10.

**Comment by fbaloca** [comment]
General event slides Quinn and I worked on: https://docs.google.com/presentation/d/1udtcYaf5LJETG4JAOvfcrwWvF_zctmFr/edit#slide=id.g2fe4d8cf79e_0_71

**Comment by fbaloca** [comment]
Survey PRA approved 9/6.

**Comment by fbaloca** [comment]
Initial events stats: https://docs.google.com/spreadsheets/d/15ch7-tcWj4Hl2he3Pk0e90gUZErawgP96VQnD8OBWvU/edit?gid=0#gid=0 Thanks for pulling reports, Quinn!

**Comment by fbaloca** [comment]
Source tracking: https://docs.google.com/spreadsheets/d/1jdF4W_DI0W2-GBkzqBsPdQzw9UfjQiBT-ADXhSOiOow/edit?gid=0#gid=0 Quinn, thanks for entering the stats from Zoom!

**Comment by kgkempe** [comment]
Summary blog post draft: https://docs.google.com/document/d/1Nv4DyTn1Bme-O6MTfLiBprdPlFfJd8B0eew9qTr7r4w/edit?usp=sharing

**Comment by fbaloca** [comment]
Survey stats: https://drive.google.com/file/d/1O8iGqID1lQi8t0FDhXlvCPxedp1TCZvz/view?usp=sharing
