### ISSUE TITLE
NASA video production

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1971]
Video Planning
- [x] Meet with challenge manager
- [x] Capture meeting notes
- [x] Update video production roles + responsibilities

Video Production
- [x] Draft script
- [x] Develop storyboard
- [x] Feedback on storyboard
- [x] Audio recording
- [x] Draft  of the video (first cut)
- [x] Feedback on video draft
- [x] Video edits
- [x] Add/edit captions
- [x] Final video

Approvals
- [x] Program
- [x] Partner
- [x] GSA 

Post and Promote
- [x] Post video on Challenge.gov YouTube
- [x] Challenge manager post link on listing
- [x] Challenge.gov social media to promote video
- [x] Challenge.gov Public Newsletter
- [x] Share with Challenge & Prize listserv

**Comment by cqslayton** [comment]
Link to draft script: https://docs.google.com/document/d/1xdJIaRlWjYrJwNTmh1kkgvSU_FfpCKCAjzqW-CBKBwg/edit

**Comment by cqslayton** [comment]
Updated script with NASA team feedback and created draft of storyboard. Approved by Jarah. Sent to CM for review 8/15. https://docs.google.com/document/d/1xdJIaRlWjYrJwNTmh1kkgvSU_FfpCKCAjzqW-CBKBwg/edit

**Comment by cqslayton** [comment]
Met with CM on 8/16 to record audio.

**Comment by cqslayton** [comment]
8/23/24: Video sent to Jeff and Amanda, and to Sarah for feedback. 

Latest version: https://drive.google.com/file/d/1rlfu6Or8wE2ua93nIBnlBqhO_J3ftmog/view?usp=drive_link

**Comment by cqslayton** [comment]
Posted on You Tube: https://youtu.be/nJeLBcb-WhI?si=kWAQ3p2Zr1H3OXrn

**Comment by cqslayton** [comment]
Sent note to Challenge and Prize community 9/18/2024: https://docs.google.com/document/d/1XRoKMK_fUwNi9xfDMm_ad2F1bL22anGMPPNT5PFUSRU/edit
