### ISSUE TITLE
Public Engagement Outreach

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1974]
As a member of the public, I want to become aware of Challenge.gov and learn about prize competitions.

- [x] Review active challenges on Challenge.gov and identify any themes or common topics
- [x] Conduct research on associations/organizations, accelerators, and innovation labs that align to the theme
- [x] Add research contacts to Public Engagement research spreadsheet with points of contact emails
- [x] Update outreach template message for current topic and activity on the site
- [x] Prepare messaging for approval and delivery

**Comment by L-Bar11** [comment]
Team provided research on several identified orgs/associations in biomedical innovation, however, it was challenging to identify personal email addresses with one exception: we identified the Regional Managing Director (Texas) and EVP, Education at Nucleate who is eager to receive more information from Jarah. 

In addition, we met internally to discuss current strategy efficiencies and delve into what's working, how we can improve, etc. and will set a rescheduled meeting date when all team members can attend and provide input.
