### ISSUE TITLE
Add Social Media Links

### ISSUE THREAD

**Issue by greensteph** [GSA/challenges-and-prizes#198]
From Lauren Rabb

the contact page https://www.challenge.gov/contact/ invites users to connect with challenge.gov on social media but I don't see any obvious social media links in the page footer or anywhere else.

**Comment by twgsa16** [comment]
Add:

Twitter: http://www.twitter.com/challengegov
Facebook: http://www.facebook.com/challengegov

**Comment by greensteph** [comment]
closed by #222
