### ISSUE TITLE
Social Media Content

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1980]
As a member of the federal and public open innovation community, I want to know about news, events, and updates for Challenge.gov and CitizenScience.gov each month.

Challenge.gov LinkedIn Content Creation
- [x] Create content to promote Challenge.gov and support challenges
- [x] Upload, tag, and publish social media content in Hootsuite
- [ ] Capture data and reporting for analysis

Challenge.gov LinkedIn Monitoring

- [x] Engage posts and content from other agencies
- [x] Continue adding to the Challenge.gov list
- [x] Monitor online activity
- [x] Support GSA social efforts

CitizenScience.gov/Open Science LinkedIn (on Challenge.gov)
- [x] Create content to promote Citizen Science/Open Science projects and content
- [x] Upload, tag, and publish social media content Hootsuite
- [x] Capture data and reporting for analysis

Challenge.gov Facebook
- [x] Create content to promote Challenge.gov and support challenges
- [x] Upload, tag, and publish social media content
- [ ] Capture data and reporting for analysis

Challenge.gov YouTube
- [ ] Upload, tag, and publish social media content Hootsuite
- [ ] Capture data and reporting for analysis

**Comment by L-Bar11** [comment]
Need to add CitizenScience.gov on Facebook
We don't publish through Hootsuite
Need to add LinkedIn Newsletter
Need to add monitoring as a task
Need to add engagement as a task
While we're not actively publishing content on Twitter for Challenge.gov and CitizenScience.gov, we still monitor notifications and mentions and also engage on tweets we're mentioned in and pull analytics. So, I'd create tasks for Twitter reflecting those.

**Comment by L-Bar11** [comment]
Added Quinn as an Assignee to this card so she can check off the CitSci content posts.

**Comment by L-Bar11** [comment]
Challenge.gov content produced, account monitored, engaged with agency partners, developed social media assets, communicated with other social media colleagues on engagement strategies.

**Comment by cqslayton** [comment]
Citizen Science/Open Science content created and shared on FB and Linked In.
