### ISSUE TITLE
July + August 2024 Data and Reporting

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1981]
- [x] Download Security Log for records

**Prepare data for Tableau**

Capture and prepare data from PMO reports
- [x] Currently published/active challenges
- [x] Challenges published
- [x] Challenges created
- [x] Number of submission by challenge
- [x] List of user accounts "created"
- [x] List of user accounts "deactivated"
- [x] List of user accounts "reactivated"
- [x] List of user accounts "decertified"
- [x] List of user accounts "recertified"

- [x] Download list of GovDelivery Challenge Followers

Capture and prepare data from social media platforms
- [x] Challenge.Gov LinkedIn (multiple reports: Followers, Visitors, Content)
- [ ] Challenge.Gov Twitter (multiple reports: By Day, By Tweet)
- [x] Challenge.Gov Facebook (multiple reports: Facebook, Hootsuite)
- [x] Challenge.Gov YouTube (multiple reports)
- [ ] CitizenScience.Gov Twitter (multiple reports: By Day, By Tweet)

Capture and prepare website data
- [x] Challenge.Gov Google Analytics
- [x] Challenge.Gov Search console
- [x] CitizenScience.Gov Google Analytics

  **- [x] Run full cycle to bring data into Tableau**
 
 
Additional data sources
- [x] Office hours
- [x] Listserv
- [x] ZenDesk
- [x] Challenge.Gov Public Newsletter
- [x] Challenge.Gov Federal Newsletter (quarterly)

**Monthly Presentation**
- [x] Review data, identify trends and insights
- [x] Prepare data presentation
- [x] Meet to review insights and make recommendations # #

**Comment by fbaloca** [comment]
Slides: https://docs.google.com/presentation/d/1v4bDFOnsKvwN4w2WMy_gIp8O9sxIwCP0KZzI4omDMAM/edit#slide=id.g2f798448b8b_0_3

**Comment by L-Bar11** [comment]
No longer able to download X/Twitter Analytics without a paid subscription.

**Comment by fbaloca** [comment]
Newsletter stats updated.

**Comment by kgkempe** [comment]
Revise data demo presentation with submission data analysis and July/August metrics
https://docs.google.com/presentation/d/1E7BdhPAzcjtYiI6ifsPPMSnYjeC_kISbTae4oImzwj0/edit?usp=sharing
