### ISSUE TITLE
Challenge Name OH Summary blog post

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1985]
**User Story**
As a PMO team member, I want to post a blog, ["What’s in a prize challenge name?"](https://docs.google.com/document/d/19pfOla8ejuQvH6GFyWdUyIH0csqB9dSwXzee73MatmM/edit?usp=sharing) on Challenge.gov.

**Acceptance Criteria**

- [x] Blog text is published on Challenge.gov on a new page
- [x] Link on Resources page is updated
- [x] Dev team notified for Pull Request

**Comment by kgkempe** [comment]
@r-bartlett-gsa - I created a new blog page for the article and updated the link for the blog on the Innovator Resources page under the 'kgkempe-1985' branch.

Will you take a look to confirm things look right and then complete the pull request? Thank you!

**Comment by r-bartlett-gsa** [comment]
> @r-bartlett-gsa - I created a new blog page for the article and updated the link for the blog on the Innovator Resources page under the 'kgkempe-1985' branch.
> 
> Will you take a look to confirm things look right and then complete the pull request? Thank you!

@kgkempe Reviewed and it looks good, here's the PR to staging site, once approved by @jarahameador , it will need a PR to prod.
https://github.com/GSA/challenges-and-prizes/pull/1986

**Comment by r-bartlett-gsa** [comment]
@kgkempe and @jarahameador Here's the PR to prod: https://github.com/GSA/challenges-and-prizes/pull/1987
