### ISSUE TITLE
FedCCS QA/QC webinar - October 22

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1993]
As a  of CitizenScience.gov federal customer, I want to learn and stay informed about leading practices for Quality Assuanace/Quality Control for federally-sponsored citizen science projects.

Event Planning

- [x] Confirm event date/time, agenda, title, and description (Kat)
- [x] Obtain approval for the event (Kat)
- [x] Add to event tracker (Kat)
- [x] Update TTS Outreach liason (Kat)

Event Promotion

- [x]  Create branding for social media (Quinn)
- [x] Develop communications plan (Kat)(
- [x] Build Zoom registration (Fil)
~~- [ ] Submit post-event survey for PRA approval (Fil)~~
- [x] Open registration and promote event (Fil)
~~- [ ] Create and publish social media (Laura)~~
~~- [ ] Add event to Challenge.gov events page (Kat)~~

Event Logistics

- [x] Content preparation (Finalize agenda, questions, and run-of-show) (Fil)
- [x] Slides Accessibility Review (Fil)
- [x] Technical rehearsal

Post Event

- [x] Send thank you and any follow up communications to speakers (Kat)
- [x] Send thank you email with survey link to registration list (Fil)
- [x] Capture, analyze, and report survey data (Fil)
- [x] Close survey (Fil)
~~- [ ] Update Challenge.gov events page to move to past events (Kat)~~

Acceptance Criteria:
Event is completed, post-event items are accomplished, data is collected and distributed, post-event artifacts (run-of-show, video, blog, etc) are delivered

**Comment by kgkempe** [comment]
Confirmed with TTS Outreach liason (Liz Camerlin) that approvals are not needed.

**Comment by fbaloca** [comment]
Basic registration created 9/11 for Jules Vastine's DOE newsletter

**Comment by kgkempe** [comment]
Check-in meeting scheduled for October 16

**Comment by cqslayton** [comment]
Prepared GSA intro slides for the event: https://docs.google.com/presentation/d/1RqdGp2oZwb59w_po7ZVX1ldJaxmqg5NK/edit?usp=drive_link&ouid=115868439013136820772&rtpof=true&sd=true

**Comment by fbaloca** [comment]
RoS completed and sent to presenters: https://docs.google.com/document/d/1TsdzNqMk9TtX5uIsEGB_UbqPI-6iW9hV-aPjg_zW-9Q/edit

**Comment by fbaloca** [comment]
Slides sent A11y checked and sent to Quinn via slack to keep PP formatting for presentation

**Comment by fbaloca** [comment]
post-event emails drafted for registrants (Jarah will send) and Listserv (John will send) https://docs.google.com/document/d/1SF0mn1m5WPsIshsXucuBiY-6d9X20gElySlVZikudCk/edit#heading=h.8yiyqd176zf

PDF of EPA/USGS presentation A11y checked and will be attached to email 
https://drive.google.com/file/d/1vqmbdLqCbldnAn2xwsdhCdlbL7ZgjUns/view?usp=sharing

**Comment by fbaloca** [comment]
Event data: https://docs.google.com/spreadsheets/d/15ch7-tcWj4Hl2he3Pk0e90gUZErawgP96VQnD8OBWvU/edit?gid=0#gid=0

**Comment by fbaloca** [comment]
Feedback survey results dashboard: https://drive.google.com/file/d/1dV2d_qvtDO-S8wpZKoHfIJ5cPjjhzVW_/view?usp=sharing
