### ISSUE TITLE
NIH Webinar - October 9, 2024

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#1996]
As a member of the federal government or the public, I want to understand how innovation is tied to NIH's mission and their approach to innovation using prize competitions.

Event Planning

- [x] Confirm event date/time, agenda, title, and description
- [x] Obtain approval
- [x] Add to event tracker
- [x] Update TTS Outreach liason

Event Promotion

- [x]  Create branding for social media 
- [x] Develop communications plan
- [x] Build Zoom registration 
- [x] Submit post-event survey for PRA approval
- [x] Open registration and promote event
- [x] Create and publish social media
- [x] Add event to Challenge.gov events page

Event Logistics

- [x] Content preparation (Finalize agenda, questions, and run-of-show)
- [x] Slides Accessibility Review
- [x] Technical rehearsal

Post Event

- [x] Send thank you and any follow up communications to speakers
- [x] Send thank you email with survey link to registration list
- [x] Capture, analyze, and report event data
- [x] Close survey
- [x] Update Challenge.gov events page to move to past events
- [x] Edit video file for accessibility
- [x] Post vidoe file on Challenge.gov YouTube channel

Acceptance Criteria:
Event is completed, post-event items are accomplished, data is collected and distributed, post-event artifacts (run-of-show, video, blog, etc) are delivered

**Comment by kgkempe** [comment]
Confirmed with TTS Outreach liason (Liz Camerlin) that approvals are not needed.

**Comment by cqslayton** [comment]
Sent [reminder invite](https://docs.google.com/document/d/1MKvXVI2QLDgMq6wb_09KOD4QQ6Hc1aTihkvXSGVUTrI/edit) to Challenge and Prize listserv 10.8.

**Comment by cqslayton** [comment]
YouTube Video is up! https://youtu.be/lI6_4m7E5dY?si=eVJWYuwQzdxa-gur

**Comment by cqslayton** [comment]
Event slides (run through accessibility) are saved and ready to share with federal community: https://drive.google.com/file/d/10XeLt0QyFqYxd2BRIJNto3cf87zO-koD/view?usp=drive_link

**Comment by fbaloca** [comment]
Post-event email with recording link and survey sent to registrants

**Comment by fbaloca** [comment]
Event stats: https://docs.google.com/spreadsheets/d/15ch7-tcWj4Hl2he3Pk0e90gUZErawgP96VQnD8OBWvU/edit?gid=0#gid=0

**Comment by fbaloca** [comment]
NIH survey dashboard: https://drive.google.com/file/d/1SWYFTqyEYj3R2cDd4UbRchXoNaBLNJI6/view?usp=sharing

**Comment by kgkempe** [comment]
Blog summary: https://docs.google.com/document/d/1EPhC2CBEZ9y8hh43s6ndW857XA6wfBuWxKKEHXm1tr0/edit?usp=sharing

Website update tracked in card #2075
