### ISSUE TITLE
September Customer Support for Challenge.gov Platform

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2010]
As a Challenge.gov customer, I want to have support using the Challenge.gov platform.

- [x] Monitor the [team@challenge.gov](mailto:team@challenge.gov) inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update [challenge tracker document](https://docs.google.com/spreadsheets/d/12nzmRrgZA6cZf032T4y9giu1b-yQbXmcsjzsYcx6h_k/edit?gid=0#gid=0)
- [x] Add ZenDesk monthly stats to PMO monthly data presentation

**Comment by cqslayton** [comment]
Tickets: 72
Public: 28
Federal: 56

Good: 9
Bad: 3

Satisfaction rating: 95%

[September 2024 Zendesk Tickets](https://drive.google.com/file/d/1Qs6M9TwMMvAkb18itq-7fOwObXVa9NZ9/view?usp=drive_link)
