### ISSUE TITLE
September 2024 Manage Challenge & Prize Listserv

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2011]
As a member of the challenge & prize community of practice, I want to be part of a well-managed email listserv.

- [x] Add new members 
- [x] Remove bounced email addresses
- [x] Review & approve listserv posts
- [x] Download and prepare listserv report
- [x] Add report to monthly data file
- [ ] _Conduct audit of listserv list to identify if any non-.gov/.mil email addresses are present (quarterly)_

**Comment by cqslayton** [comment]
Subscribers: 711
Added: 2
Autodelete: 5
Approved posts: 4
Sign off: 1

[September Listserv Activity](https://drive.google.com/file/d/19j4DOqmsQ9tA5h0bDpqYCAl09rcZupQ4/view?usp=drive_link)
[September Listserv Subscribers](https://drive.google.com/file/d/1v7Q0ufYYVZA-gk_sQaNyMe4cu-9plbx6/view?usp=drive_link)
