### ISSUE TITLE
September Social Media Content

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2012]
As a member of the federal and public open innovation community, I want to know about news, events, and updates for Challenge.gov and CitizenScience.gov each month.

Challenge.gov LinkedIn Content Creation
- [x] Create content to promote Challenge.gov and support challenges
- [x] Upload, tag, and publish social media content
- [x] Capture data and reporting for analysis

Challenge.gov LinkedIn Newsletter
- [x] Create content to promote Challenge.gov and support challenges
- [x] Upload, tag, and publish social media content
- [x] Capture data and reporting for analysis

Challenge.gov LinkedIn Monitoring
- [x] Engage posts and content from other agencies
- [x] Continue adding to the Challenge.gov list
- [x] Monitor online activity
- [x] Support GSA social efforts

CitizenScience.gov/Open Science LinkedIn (on Challenge.gov)
- [x] Create content to promote Citizen Science/Open Science projects and content
- [x] Upload, tag, and publish social media content
- [x] Capture data and reporting for analysis

Challenge.gov Facebook
- [x] Create content to promote Challenge.gov and support challenges
- [x] Upload, tag, and publish social media content
- [x] Capture data and reporting for analysis

Challenge.gov Facebook Monitoring
- [x] Engage posts and content from other agencies
- [x] Continue adding to the Challenge.gov list
- [x] Monitor online activity
- [x] Support GSA social efforts

CitizenScience.gov/Open Science Facebook (on Challenge.gov)
- [x] Create content to promote Citizen Science/Open Science projects and content
- [x] Upload, tag, and publish social media content 
- [x] Capture data and reporting for analysis

Challenge.gov YouTube
- [x] Upload, tag, and publish social media content 
- [x] Capture data and reporting for analysis

**Comment by L-Bar11** [comment]
Can we either add a line under "LinkedIn Content Creation" specifically for LinkedIn Newsletter or make it's own section (content creations, asset design, publishing as tasks underneath)?

**Comment by L-Bar11** [comment]
Fil has been tagged for final review of LinkedIn newsletter, then I will share with Jarah for approval and launch.
