### ISSUE TITLE
A11y scanning integration for challenges-and-prizes: axe

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/challenges-and-prizes#2013]
As a site engineer, in order to ensure the quality and accessibility of our code, I would like an automated accessibility tool to test all our of code.

Acceptance criteria:

- [x] [axe-core-rspec](https://github.com/dequelabs/axe-core-gems/tree/develop/packages/axe-core-rspec) is implemented for challenges-and-prizes repo and can be turned on to auto-run with the other CI tests at a later time (update library link in the AC)
- [x] A one time manual scan report is shared with the team

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Please share a link to the report in this issue as well.

**Comment by TCKapGrp** [comment]
@jairoanaya , if the AC is done, can you please check them off on this card?  Thank you!

**Comment by jairoanaya** [comment]
Summary of work:

1. Reusing and installing accessibility test Challenge_gov scripts on Challenges and Prizes.
2. Preparing and Sending reports to Team with all Challenges  https://drive.google.com/drive/folders/1qimVVwHosFEc6zAeOhNLpOpZ-Kc34lNS
3. Generate all Challenges & Prizes URLs to test.
4. Updating the script to generate CSV files for nondevelopers. 
5. Deploying the solution.

You can explore the final results and further instructions here: https://drive.google.com/drive/folders/1yvUtQe-SRVJc-p1n1nMzS6fuykZUISit?usp=drive_link

**Comment by mhotch24** [comment]
Completed review and recommendations. Documented here: https://docs.google.com/document/d/19CA_jlKCcTX9rEbgGSzjY3h8UEyGLU7T3ighHLkmKVw/edit
