### ISSUE TITLE
Office Hour 66 - September 25

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2021]
As a member of the challenge & prize community of practice, I want an opportunity to connect with other challenge practitioners, learn about the practice of running federal prize competitions, and understand how Challenge.gov can support my agency's prize competition strategy.

**Pre-event**

- [x] Choose topic and identify guest speakers
- [x] Send invites to speakers
- [x] Draft invite
- [x] Send invite to Listserv
- [x] Create a calendar invitation
- [x] Approve registrations
- [x] Download registrations
- [x] Updated calendar invite with registrations as needed
- [x] Send reminder the day before

**Event**

- [x] Approve any last minute registrations
- [x] Open Zoom meeting 5 minutes before
- [x] Assign co-host as needed
- [x] Take attendance
- [x] Take notes

**Post event**

- [x] Report out
- [x] Write summary content for blog

**Comment by cqslayton** [comment]
Blog draft: https://docs.google.com/document/d/1trZfXIlBe78YYTGVK2UHvo6jZiO8dK9MH-G25LNEmn8/edit

Event data; https://drive.google.com/drive/folders/1UmaN3LQebL-5Hy1ybLm7kqSMutzf3AH1

- Registrations: 35
- Attendees: 11
- Attendance rate: 31%
- Agencies represented reg: 15
- Agencies rep. attendees: 4
- Questions submitted at registration: 0

**Comment by cqslayton** [comment]
Blog approved - waiting for approval from Liz Cammerlin.
