### ISSUE TITLE
Challenges-and-prizes Dependabot alerts

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/challenges-and-prizes#2024]
- [x] Review [dependabot alerts](https://github.com/GSA/challenges-and-prizes/security/dependabot) and resolve all challenges-and-prizes repo vulnerabilities during sprint 10/8/24
  - [x]  Document below which items are being worked on / resolved
- [x]  Update the items that do not apply to challenges-and-prizes

**Comment by r-bartlett-gsa** [comment]
GSA alert was received about this vulnerability: https://github.com/advisories/GHSA-6f62-3596-g6w7

**Comment by jdonis** [comment]
Here is the document with some screenshots about the dependabots solved 
https://docs.google.com/document/d/16Koh-mXE8OUfrPcztPcpyx_r_v7N_444ROm1nBQlRHI/edit?usp=sharing
