### ISSUE TITLE
October Customer Support for Challenge.gov Platform

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2037]
As a Challenge.gov customer, I want to have support using the Challenge.gov platform.

Acceptance criteria:
Inbox messages are monitored, tickets assigned, demos with customers scheduled as needed, challenge tracker is updated, ZenDesk metrics are captured for reporting.

**October 1 - 7**
- [x] Monitor the [team@challenge.gov](mailto:team@challenge.gov) inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update [challenge tracker document](https://docs.google.com/spreadsheets/d/12nzmRrgZA6cZf032T4y9giu1b-yQbXmcsjzsYcx6h_k/edit?gid=0#gid=0)

---
**October 8 - 14**
- [x] Monitor the [team@challenge.gov](mailto:team@challenge.gov) inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update [challenge tracker document](https://docs.google.com/spreadsheets/d/12nzmRrgZA6cZf032T4y9giu1b-yQbXmcsjzsYcx6h_k/edit?gid=0#gid=0)

---
**October 15 - 21**
- [x] Monitor the [team@challenge.gov](mailto:team@challenge.gov) inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update [challenge tracker document](https://docs.google.com/spreadsheets/d/12nzmRrgZA6cZf032T4y9giu1b-yQbXmcsjzsYcx6h_k/edit?gid=0#gid=0)

---
**October 22 - 31**
- [x] Monitor the [team@challenge.gov](mailto:team@challenge.gov) inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update [challenge tracker document](https://docs.google.com/spreadsheets/d/12nzmRrgZA6cZf032T4y9giu1b-yQbXmcsjzsYcx6h_k/edit?gid=0#gid=0)

---
Monthly Task
- [x] Add ZenDesk monthly stats to PMO monthly data presentation

**Comment by cqslayton** [comment]
Total tickets: 65
Public: 29
Federal: 35
Contractor: 1
Satisfaction rate: 100%
Good: 10
Bad: 0

Comments:

- The response was quick and to the point. Many thanks for your assistance.
- Timely response.
- I had actually found the document I was asking for but I am happy that GSA followed up. Thank you!
- Stellar, especially with a disability
