### ISSUE TITLE
October 2024 Manage Challenge & Prize Listserv

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2038]
As a member of the challenge & prize community of practice, I want to be part of a well-managed email listserv.

Acceptance criteria:
Listserv message are reviewed & approved, new members added, bounced emails removed, listserv report captured for data analysis.

**October 1- 7**
- [x] Add new members 
- [x] Remove bounced email addresses
- [x] Review & approve listserv posts

**October 8 - 14**
- [x] Add new members 
- [x] Remove bounced email addresses
- [x] Review & approve listserv posts

**October 15 - 21**
- [x] Add new members 
- [x] Remove bounced email addresses
- [x] Review & approve listserv posts

**October 22 - 31**
- [x] Add new members 
- [x] Remove bounced email addresses
- [x] Review & approve listserv posts

**Monthly tasks**
- [x] Download and prepare listserv report
- [x] Add report to monthly data file
- [ ] _Conduct audit of listserv list to identify if any non-.gov/.mil email addresses are present (quarterly)_

**Comment by cqslayton** [comment]
Listserv activity report October 2024: https://drive.google.com/file/d/1vM5di01n6xASjSMFj9_JdqsTSY-CqH6l/view?usp=drive_link

710 subscribers
