### ISSUE TITLE
Challenge Manager Communications and Outreach Support

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2040]
User Story:
As a challenge manager with a prize competition on Challenge.gov, I want to understand how to partner with Challenge.gov to promote my prize competition, along with tips and leading practices for prize competition promotion.

Acceptance Criteria:
Challenge.gov PMO team hosts a stand alone session focused on communications and outreach for challenge managers with open challenges on Challenge.gov.

- [x] Plan session roles and discussion agenda
- [x] Schedule session
- [x] Send email invitations
- [x] Set up ZoomGov registration and collect questions
- [x] Host session
- [x] Capture key discussion topics
- [x] Send post-event survey and materials (wrap up)

**Comment by L-Bar11** [comment]
@kgkempe I'd like to take part in the questions asked for registration if possible, thanks!

**Comment by L-Bar11** [comment]
Need to create graphic to brand this.
Need to place immediate "holds" on date/time for Challenge.gov team

**Comment by L-Bar11** [comment]
Event Brief: https://docs.google.com/document/d/1wIRcTDKEwk7RJA9UciD5t8S9_imAwlzh6wQ_hdRUVMg/edit

**Comment by cqslayton** [comment]
Registration page: https://gsa.zoomgov.com/meeting/register/vJIsf--pqzsrG5k_b2mIiBPP5lA-jWqvfos

**Comment by L-Bar11** [comment]
Sent event brief to Jarah for review/approval on Friday, Oct. 18. Upon feedback/approval, will coordinate with Quinn/Fil to send invites out.
