### ISSUE TITLE
CitizenScience.gov update contact info for NOAA NWS COOP

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2052]
**User Story**

As a member of the public, I want to accurately contact NOAA's [National Weather Service Cooperative Observer Program](https://youtu.be/X07mBq2tnMg?si=mhOZIPz7ZEKYLnex).

**Acceptance Criteria**

- [x] Update contact information on NWS COOP program page
- [x] Notify dev team for content update

**Comment by kgkempe** [comment]
Content updated in 10-22-2024-cqslayton branch

**Comment by r-bartlett-gsa** [comment]
This update is completed and merged to production: https://github.com/GSA/citizenscience.gov/pull/427
