### ISSUE TITLE
November Customer Support for Challenge.gov Platform

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2063]
As a Challenge.gov customer, I want to have support using the Challenge.gov platform.

Acceptance criteria:
Inbox messages are monitored, tickets assigned, demos with customers scheduled as needed, challenge tracker is updated, ZenDesk metrics are captured for reporting.

**November 1 - 7**
- [x] Monitor the [team@challenge.gov](mailto:team@challenge.gov) inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update [challenge tracker document](https://docs.google.com/spreadsheets/d/12nzmRrgZA6cZf032T4y9giu1b-yQbXmcsjzsYcx6h_k/edit?gid=0#gid=0)

---
**November 8 - 14**
- [x] Monitor the [team@challenge.gov](mailto:team@challenge.gov) inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update [challenge tracker document](https://docs.google.com/spreadsheets/d/12nzmRrgZA6cZf032T4y9giu1b-yQbXmcsjzsYcx6h_k/edit?gid=0#gid=0)

---
**November 15 - 21**
- [x] Monitor the [team@challenge.gov](mailto:team@challenge.gov) inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update [challenge tracker document](https://docs.google.com/spreadsheets/d/12nzmRrgZA6cZf032T4y9giu1b-yQbXmcsjzsYcx6h_k/edit?gid=0#gid=0)

---
**November 22 - 30**
- [x] Monitor the [team@challenge.gov](mailto:team@challenge.gov) inbox/ZenDesk
- [x] Provide tier 1 support to federal challenge managers and public solvers
- [x] Assign tickets in Zen Desk to team members based on needs
- [x] Set up demos with customers as needed
- [x] Update [challenge tracker document](https://docs.google.com/spreadsheets/d/12nzmRrgZA6cZf032T4y9giu1b-yQbXmcsjzsYcx6h_k/edit?gid=0#gid=0)

---
Monthly Task
- [x] Add ZenDesk monthly stats to PMO monthly data presentation

**Comment by cqslayton** [comment]
November 2024 Zendesk tickets report: https://drive.google.com/file/d/11qgRv1jwENy3JneZjEqkpQcVG2b5W3Ib/view?usp=drive_link
