### ISSUE TITLE
Pages Accessibility Report Fixes - 2536

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/challenges-and-prizes#2065]
- [ ] Remediate Pages accessibility scan issues for challenges-and-prizes: https://pages.cloud.gov/report/2536

**Comment by jairoanaya** [comment]
@r-bartlett-gsa the accessibility report has been resolved as show in the image. 

Changes were made on: challenge_gov and challenges-and-prizes. See details here:

https://github.com/GSA/challenges-and-prizes/pull/2092/commits/cf899c6bc13564d535b34163a8853df1b8eef8ca
https://github.com/GSA/challenges-and-prizes/pull/2093/commits/c9d9f2701c06b7c17124ead81c01d455a0768847
https://github.com/GSA/challenges-and-prizes/pull/2082/commits/a8a9040502649c1295051e4a44708d309b32935b


2 Suppressions made for the report. See more https://pages.cloud.gov/report/4210
![Image](https://github.com/user-attachments/assets/10035dce-abc4-4161-947d-74dbc34097e3)
