### ISSUE TITLE
Challenges-and-prizes Dependabot alerts

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/challenges-and-prizes#2066]
- [x] Review [dependabot alerts](https://github.com/GSA/challenges-and-prizes/security/dependabot) and resolve all challenges-and-prizes repo vulnerabilities during sprint 10/8/24
  - [x]  Document below which items are being worked on / resolved
- [ ]  Update the items that do not apply to challenges-and-prizes

**Comment by jairoanaya** [comment]
Bumps [rexml](https://github.com/ruby/rexml) from 3.3.7 to 3.3.9.
