### ISSUE TITLE
Challenge Manager Communications and Outreach Support - December 4, 2024

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2078]
User Story:
As a challenge manager with a prize competition on Challenge.gov, I want to understand how to partner with Challenge.gov to promote my prize competition, along with tips and leading practices for prize competition promotion.

Acceptance Criteria:
Challenge.gov PMO team hosts a stand alone session focused on communications and outreach for challenge managers with open challenges on Challenge.gov.

- [x] Plan session roles and discussion agenda
- [x] Schedule session
- [x] Send email invitations
- [x] Set up ZoomGov registration and collect questions
- [x] Pull registration list to review questions/comments
- [x] Send reminder email
- [x] Host session
- [x] 'Thanks for attending' email (with session materials attachments)

**Comment by kgkempe** [comment]
Updated event brief: https://docs.google.com/document/d/1wIRcTDKEwk7RJA9UciD5t8S9_imAwlzh6wQ_hdRUVMg/edit?usp=sharing

Sent invitaitons on November 25

**Comment by L-Bar11** [comment]
I just added a task to "Pull registration list to review questions/comments" so I can review two days prior to event.
