### ISSUE TITLE
CitizenScience.gov project updates

### ISSUE THREAD

**Issue by kgkempe** [GSA/challenges-and-prizes#2080]
**User Story**
As a user of CitizenScience.gov, I want to have an updated and accurate cataloge of federally-sponosred citizen science projects.

**Acceptance Criteria**
Update catalog with two new projects from NASA (Eclipse Megamovie 2024 (EM2024) and Integrating Remote Sensing and Citizen Science to Support Conservation of Woodland Vernal Pools) and USDA (Grow for Tomorrow)

- [x] Alert agency Citizen Science coordinator of new project
- [x] Receive project approval from agency Citizen Science coordinator
- [x] Update content in new branch on CitizenScience.gov
- [x] Notify dev team to publish

**Comment by cqslayton** [comment]
Sent projects to CitSci Coordinators for approval. Added checkboxes to card for this task.

**Comment by cqslayton** [comment]
Updated links @r-bartlett-gsa:

- Phytokplankton Monitoring network (https://www.citizenscience.gov/catalog/87/#):  https://coastalscience.noaa.gov/monitoring-and-assessments/pmn/
- FCC Speed test case study: https://www.fcc.gov/BroadbandData

**Comment by cqslayton** [comment]
Sprint 106 projects to add @cqslayton - branch is "12-11-2024-cqslayton"

- Eclipse Megamovie 2024 (EM2024), NASA

- Grow for Tomorrow!, USDA
