### ISSUE TITLE
Add og Metadata for Challenges

### ISSUE THREAD

**Issue by greensteph** [GSA/challenges-and-prizes#211]
**Current:**
<img width="616" alt="Screenshot 2019-06-27 09 30 58" src="https://user-images.githubusercontent.com/11343071/60279463-517f0d80-98be-11e9-8194-a28b60bd4031.png">

**Comment by greensteph** [comment]
Should be able to:
 -fix the challenge logo in the main card preview
 -pull in the card image for challenges
 -change the page title to the challenge title for challenges
 -use the tagline as the og description

**Comment by greensteph** [comment]
New site wide card preview with image.

<img width="588" alt="Screenshot 2019-07-16 05 59 02" src="https://user-images.githubusercontent.com/11343071/61292595-e6bf4480-a78e-11e9-9a86-0a58e5ab03f7.png">

**Comment by twgsa16** [comment]
Check out this post on LinkedIN: https://www.linkedin.com/posts/gabemounce_air-force-offers-15000-for-help-from-public-activity-6556778779161825280-GNoj -- it looks like challenge.gov pulled in a reference to the Boldline Challenge. Can you take a look?

**Comment by greensteph** [comment]
@twgsa16 The link she posted was https://www.challenge.gov/list/ which is no longer a link for us.

**Comment by greensteph** [comment]
New preview for challenges

<img width="585" alt="Screenshot 2019-07-18 06 07 54" src="https://user-images.githubusercontent.com/11343071/61456120-7fd29480-a922-11e9-8a53-af1a481f4274.png">

**Comment by greensteph** [comment]
Current LinkedIn preview

<img width="1311" alt="Screenshot 2019-07-18 07 27 49" src="https://user-images.githubusercontent.com/11343071/61461260-9af6d180-a92d-11e9-891a-64474601efae.png">

**Comment by greensteph** [comment]
New previews for challenges on Twitter, Facebook, & LinkedIn: 
#265 

<img width="1338" alt="Screenshot 2019-07-23 07 26 38" src="https://user-images.githubusercontent.com/11343071/61715922-5ac39480-ad1b-11e9-87fd-790966e8eb66.png">
<img width="1301" alt="Screenshot 2019-07-23 07 27 16" src="https://user-images.githubusercontent.com/11343071/61715927-5e571b80-ad1b-11e9-8be4-3dd20f817527.png">
<img width="1251" alt="Screenshot 2019-07-23 07 28 23" src="https://user-images.githubusercontent.com/11343071/61715993-7c248080-ad1b-11e9-9858-732ff8cf246e.png">
