### ISSUE TITLE
Needs Tagline: PROOF: The ChemBio Suit Design Challenge

### ISSUE THREAD

**Issue by greensteph** [GSA/challenges-and-prizes#519]
Challenge: [**PROOF: The ChemBio Suit Design Challenge**](https://www.challenge.gov/challenge/proof-the-chembio-suit-design-challenge/)

add Tagline: Choosing the right protective gear

This info was not included when the external challenge was created.

**Comment by twgsa16** [comment]
@greensteph - This challenge did not appear to have a tagline based on the screenshots on WayBack Machine, but it was included in the data? Can add, but just wanted to double-check.
<img width="1426" alt="Screen Shot 2020-03-04 at 11 29 16 AM" src="https://user-images.githubusercontent.com/16917415/75900973-ce7a6380-5e0b-11ea-8055-f0e3876f2b9a.png">
<img width="1428" alt="Screen Shot 2020-03-04 at 11 29 56 AM" src="https://user-images.githubusercontent.com/16917415/75900981-d1755400-5e0b-11ea-9ce5-4bfe97751cb2.png">

**Comment by greensteph** [comment]
@twgsa16 It's in their external link.
